---
# MongoDB Replica Set Inventory
# Rocky Linux 9.4 MongoDB Cluster

all:
  children:
    mongodb:
      hosts:
        mongodb1:
          ansible_host: 172.16.90.163
          mongodb_role: secondary
          mongodb_priority: 1
        mongodb2:
          ansible_host: 172.16.90.164
          mongodb_role: primary
          mongodb_priority: 2
        mongodb3:
          ansible_host: 172.16.90.165
          mongodb_role: secondary
          mongodb_priority: 1
      vars:
        ansible_user: root
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

    # Optional: separate group for monitoring/backup servers
    monitoring:
      hosts: {}
